### ISSUE TITLE
workspace visualisation methods

### ISSUE THREAD

**Issue by sneumann** [meowcat/RMassBank#28]
_Issue by **[sneumann](https://github.com/sneumann)** from Tuesday Oct 22, 2013 at 07:17 GMT_
_Originally opened as https://github.com/sneumann/RMassBank/issues/20_

----

It'd be great to have some basic visualisation methods for spectra in a Workspace. The next step after that would be to be able to compare two spectra (up-down plot) from different workspaces, to compare e.g. different workflows.

**Comment by schymane** [comment]
Close this for now, we can add a new issue if we want new plots
