### ISSUE TITLE
Waters data

### ISSUE THREAD

**Issue by schymane** [meowcat/RMassBank#82]
Other updates to the XCMS Online are: 
•	Waters Instrument users now have a reader for RAW data on XCMS Online
Follow-up?

**Comment by schymane** [comment]
We can either work around via xcmsRaw and get to waters via netCDF. Closing for now

**Comment by kamakamadaun** [comment]
To update this. Newer versions of Proteowizard should work. It is unclear if the lockmassrefiner needs to be used. It apparently depends on the version of masslynx installed and what was used to generate the data. it is a big mess.

**Comment by stanstrup** [comment]
To update this. Newer versions of Proteowizard should work. It is unclear if the lockmassrefiner needs to be used. It apparently depends on the version of masslynx installed and what was used to generate the data. it is a big mess.
